package tui

import (
	"strings"
	"testing"

	"github.com/gdamore/tcell/v2"
)

// TestBothTablesCarryEveryRole is the check that catches a role added to one table
// and not the other.
//
// It is against the role list rather than against the other table, because two tables
// compared only to each other would both be missing the same role and the comparison
// would pass. A role rendered as chrome because a table lacked it is a row a reader
// cannot tell from the frame around it.
func TestBothTablesCarryEveryRole(t *testing.T) {
	for _, ground := range []Ground{GroundDark, GroundLight} {
		table := RoleTableFor(ground)
		for _, role := range Roles() {
			if _, ok := table[role]; !ok {
				t.Errorf("the %v table has no %s", ground, RoleName(role))
			}
		}
		if got, want := len(table), len(roleOrder); got != want {
			t.Errorf("the %v table carries %d roles, want %d", ground, got, want)
		}
	}
}

// TestTheThreeStatesAreDistinct is a property rather than a shape, and it is the one
// that decides whether a reader can read a refusal.
//
// Dim is present but not the point, failure is something went wrong, and approval is a
// question asking the reader to do something. A reader who cannot tell an approval
// from a failure cannot tell a question from a complaint.
func TestTheThreeStatesAreDistinct(t *testing.T) {
	for _, ground := range []Ground{GroundDark, GroundLight} {
		table := RoleTableFor(ground)
		t.Run(ground.String(), func(t *testing.T) {
			assertDistinct(t, table,
				[]Role{RoleDim, RoleFailure, RoleApproval},
				"the three state roles must not collide")
			assertDistinct(t, table,
				[]Role{RoleFailure, RoleApproval, RoleSuccess},
				"failure, approval and success must not collide")
		})
	}
}

// TestTheThreeToolIdentitiesAreDistinct covers the property that makes a tool line
// readable. A reader who cannot tell a file read from a command cannot read the log,
// so the three are separate roles and separate values.
func TestTheThreeToolIdentitiesAreDistinct(t *testing.T) {
	for _, ground := range []Ground{GroundDark, GroundLight} {
		table := RoleTableFor(ground)
		t.Run(ground.String(), func(t *testing.T) {
			assertDistinct(t, table,
				[]Role{RoleToolFS, RoleToolGit, RoleToolShell},
				"the three tool identities must not collide")

			// And against the states, since a tool line and a refusal are both
			// single rows in a log and the reader is looking at both.
			for _, tool := range []Role{RoleToolFS, RoleToolGit, RoleToolShell} {
				for _, state := range []Role{RoleDim, RoleFailure, RoleApproval} {
					if table[tool] == table[state] {
						t.Errorf("%s and %s are both %s",
							RoleName(tool), RoleName(state), table[tool].Hex())
					}
				}
			}
		})
	}
}

// assertDistinct reports each pair in a set that carries the same colour.
func assertDistinct(t *testing.T, table RoleTable, roles []Role, why string) {
	t.Helper()

	for i := range roles {
		for j := i + 1; j < len(roles); j++ {
			if table[roles[i]] == table[roles[j]] {
				t.Errorf("%s: %s and %s are both %s",
					why, RoleName(roles[i]), RoleName(roles[j]), table[roles[i]].Hex())
			}
		}
	}
}

// TestTheTwoGroundsReadDifferently checks that the second table is a table and not a
// copy. A light reader and a dark reader see different colours, and that is the
// reason there are two.
func TestTheTwoGroundsReadDifferently(t *testing.T) {
	dark, light := RoleTableFor(GroundDark), RoleTableFor(GroundLight)

	same := 0
	for _, role := range Roles() {
		if dark[role] == light[role] {
			same++
		}
	}
	if same == len(roleOrder) {
		t.Error("the two tables are identical, so one of them is not a table")
	}
	if same > len(roleOrder)/2 {
		t.Errorf("%d of %d roles carry the same colour in both tables",
			same, len(roleOrder))
	}
}

// TestTheLightTableIsDarker covers the reason the second table exists and is not
// generated by inverting the first.
//
// A value chosen to read as emphasis on a dark ground is unreadable as emphasis on a
// light one, so the light table holds darker values for the same roles rather than
// paler ones. A test on the average catches a table that got the direction wrong
// without a reader noticing.
func TestTheLightTableIsDarker(t *testing.T) {
	dark, light := RoleTableFor(GroundDark), RoleTableFor(GroundLight)

	var darkSum, lightSum float64
	for _, role := range Roles() {
		darkSum += float64(dark[role].R) + float64(dark[role].G) + float64(dark[role].B)
		lightSum += float64(light[role].R) + float64(light[role].G) + float64(light[role].B)
	}

	if lightSum >= darkSum {
		t.Errorf("the light table averages %.0f against the dark table's %.0f: it should be darker",
			lightSum/float64(len(roleOrder)*3), darkSum/float64(len(roleOrder)*3))
	}
}

// TestGroundIsLightJudgesByLuminance covers the choice of formula rather than an
// average.
//
// The eye is not equally sensitive to each channel, so an average calls a saturated
// blue brighter than a mid grey when it is not. This case is the one that separates
// the two: a mid grey sits above the midpoint on an average and below it on
// luminance.
func TestGroundIsLightJudgesByLuminance(t *testing.T) {
	cases := []struct {
		name string
		bg   string
		want bool
	}{
		{"white is light", "#ffffff", true},
		{"near-white is light", "#f5f5f5", true},
		{"mid grey is dark", "#808080", false},
		{"near-black is dark", "#0a0a0a", false},
		{"black is dark", "#000000", false},
		// A saturated blue is brighter than a mid grey as an average of the
		// channels and darker on luminance, which is the whole reason for the
		// formula. Judged as light, a blue background picks the wrong table.
		{"saturated blue is dark", "#0000ff", false},
		{"saturated yellow is light", "#ffff00", true},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			theme, err := NewTheme("test", "", c.bg)
			if err != nil {
				t.Fatalf("NewTheme: %v", err)
			}
			if got := groundIsLight(GroundAuto, &theme); got != c.want {
				t.Errorf("groundIsLight with background %s is %v, want %v",
					c.bg, got, c.want)
			}
		})
	}
}

// TestAnExplicitChoiceBeatsTheTheme covers the order, and each step of it is a
// reason. A reader who has said which ground they are on has said it more recently
// than a file did.
func TestAnExplicitChoiceBeatsTheTheme(t *testing.T) {
	onLight := themeWith(t, "", "#ffffff")
	onDark := themeWith(t, "", "#101010")

	if groundIsLight(GroundDark, &onLight) {
		t.Error("a light theme overrode an explicit dark")
	}
	if !groundIsLight(GroundLight, &onDark) {
		t.Error("a dark theme overrode an explicit light")
	}
}

// TestABackgroundThatCannotBeReadFallsToDark covers the case where the theme names
// none. A background the client cannot read is not a background it judges against.
func TestABackgroundThatCannotBeReadFallsToDark(t *testing.T) {
	if groundIsLight(GroundAuto, nil) {
		t.Error("no theme was read as light")
	}

	none := themeWith(t, "", "")
	if groundIsLight(GroundAuto, &none) {
		t.Error("a theme naming no background was read as light")
	}
}

// themeWith builds a theme and fails the test if it cannot.
func themeWith(t *testing.T, fg, bg string) Theme {
	t.Helper()

	theme, err := NewTheme("test", fg, bg)
	if err != nil {
		t.Fatalf("NewTheme(%q, %q): %v", fg, bg, err)
	}
	return theme
}

// TestParseGroundRefusesWhatItDoesNotKnow covers the decision to error rather than
// fall back.
//
// A reader who typed a word and got the default back would conclude the command
// ignored them, so an unrecognised ground is refused by name.
func TestParseGroundRefusesWhatItDoesNotKnow(t *testing.T) {
	for _, in := range []string{"auto", "AUTO", " dark ", "Light"} {
		if _, err := ParseGround(in); err != nil {
			t.Errorf("ParseGround(%q) returned %v, want it read", in, err)
		}
	}

	for _, in := range []string{"", "grey", "no", "lightt"} {
		_, err := ParseGround(in)
		if err == nil {
			t.Errorf("ParseGround(%q) was accepted, want a refusal", in)
			continue
		}
		if !strings.Contains(err.Error(), "auto, dark or light") {
			t.Errorf("the refusal is %q, want it to name what is allowed", err)
		}
	}
}

// TestColourOffWritesNothing is the property the plain-text contract rests on at the
// other end. A row is plain text and the colour travels beside it, so a palette with
// colour off contributes no bytes at all.
func TestColourOffWritesNothing(t *testing.T) {
	p := NewPalette(false, GroundDark, nil)

	for _, role := range Roles() {
		if got := p.Sequence(role); got != "" {
			t.Errorf("%s wrote %q with colour off", RoleName(role), got)
		}
	}
	if got := p.Base(); got != "" {
		t.Errorf("the base wrote %q with colour off", got)
	}
	if got := p.Reset(); got != bareReset {
		t.Errorf("the reset is %q, want the bare reset with colour off", got)
	}
}

// TestResetCarriesTheBase covers the case that a bare reset alone gets wrong.
//
// A bare reset clears the foreground and the background, so the rest of the row after
// it is drawn in the terminal theme rather than on the theme background. The reset is
// therefore the bare one followed by the base.
func TestResetCarriesTheBase(t *testing.T) {
	theme := themeWith(t, "#d0d0d0", "#101010")
	p := NewPalette(true, GroundDark, &theme)

	reset := p.Reset()
	if !strings.HasPrefix(reset, bareReset) {
		t.Errorf("the reset is %q, want it to begin with the bare reset", reset)
	}
	if !strings.HasSuffix(reset, p.Base()) {
		t.Errorf("the reset is %q, want it to end with the base %q", reset, p.Base())
	}
}

// TestTheGroundSettlesWithColourOff covers a small decision worth stating. A reader
// who asks which table would be read is answered without turning colour on, so the
// ground does not depend on the flag.
func TestTheGroundSettlesWithColourOff(t *testing.T) {
	light := themeWith(t, "", "#ffffff")

	if got := NewPalette(false, GroundAuto, &light).Ground(); got != GroundLight {
		t.Errorf("with colour off the ground is %v, want light", got)
	}
	if NewPalette(false, GroundAuto, &light).On() {
		t.Error("a palette built with colour off reports itself as on")
	}
}

// TestAnUnknownRoleReadsAsChrome covers the fallback. A row with no colour in it is
// readable and a draw that refuses leaves the reader with a blank row.
func TestAnUnknownRoleReadsAsChrome(t *testing.T) {
	p := NewPalette(true, GroundDark, nil)
	unknown := Role(99)

	if got, want := p.Sequence(unknown), p.Sequence(RoleChrome); got != want {
		t.Errorf("an unknown role wrote %q, want chrome %q", got, want)
	}
}

// TestFaintDimIsAnAlternativeNotADefault covers the unverified case. Whether a
// terminal draws faint text is not known from here, so it is offered and the default
// stays a colour.
func TestFaintDimIsAnAlternativeNotADefault(t *testing.T) {
	plain := NewPalette(true, GroundDark, nil)
	faintDim := plain.WithFaintDim()

	if got := plain.Sequence(RoleDim); got == faintSequence {
		t.Error("dim defaults to the faint attribute")
	}
	if got := faintDim.Sequence(RoleDim); got != faintSequence {
		t.Errorf("the faint palette writes %q for dim, want the faint attribute", got)
	}

	// And only dim changes. The faint attribute is an alternative to one colour
	// and not to the table.
	if got, want := faintDim.Sequence(RoleChrome), plain.Sequence(RoleChrome); got != want {
		t.Errorf("faint changed chrome to %q, want %q", got, want)
	}
}

// TestRoleNameCoversEveryRole keeps a diagnostic honest. A role with no name is a role
// a message cannot identify.
func TestRoleNameCoversEveryRole(t *testing.T) {
	for _, role := range Roles() {
		name := RoleName(role)
		if name == "" || strings.HasPrefix(name, "role(") {
			t.Errorf("role %d reads as %q, want a name", int(role), name)
		}
	}
	if RoleName(Role(99)) == "" {
		t.Error("an unknown role has an empty name")
	}
}

// TestRGBRoundTrips covers the hex reading, since a theme is written by a reader and
// an authored colour has to land exactly.
func TestRGBRoundTrips(t *testing.T) {
	const hex = "#3b82f6"

	rgb, ok := RGBFromHex(hex)
	if !ok {
		t.Fatalf("RGBFromHex(%q) refused a well formed colour", hex)
	}
	if got := rgb.Hex(); got != hex {
		t.Errorf("the round trip gave %q, want %q", got, hex)
	}
}

// TestRGBRefusesWhatIsNotAColour covers the form. A theme names a colour in a
// document rather than at a prompt, and a value with spaces in it is one that was
// assembled rather than written.
func TestRGBRefusesWhatIsNotAColour(t *testing.T) {
	for _, in := range []string{"", "3b82f6", "#3b82f", "#3b82f6ff", "#gggggg", "# 3b82f6"} {
		if _, ok := RGBFromHex(in); ok {
			t.Errorf("RGBFromHex(%q) accepted it, want a refusal", in)
		}
	}
}

// TestNewThemeRefusesAnUnreadableColour covers the decision to error rather than
// fall back. A reader who wrote a wrong value and got the terminal theme back would
// conclude colour is off rather than that the value is wrong, and those are fixed
// differently.
func TestNewThemeRefusesAnUnreadableColour(t *testing.T) {
	if _, err := NewTheme("bad", "#gggggg", ""); err == nil {
		t.Error("a theme with an unreadable foreground was accepted")
	}
	if _, err := NewTheme("bad", "", "nonsense"); err == nil {
		t.Error("a theme with an unreadable background was accepted")
	}

	theme, err := NewTheme("partial", "", "#101010")
	if err != nil {
		t.Fatalf("a theme naming one side: %v", err)
	}
	if _, ok := theme.ForegroundRGB(); ok {
		t.Error("a theme naming no foreground reported one")
	}
	if _, ok := theme.BackgroundRGB(); !ok {
		t.Error("a theme naming a background did not report it")
	}
}

// TestSequenceWritesDirectRGB covers the reversal recorded in the design.
//
// The direct-RGB form rather than a 256-colour index, because the reason the mapping
// existed, Terminal.app support, did not survive the decision.
func TestSequenceWritesDirectRGB(t *testing.T) {
	got := RGB{R: 0x3b, G: 0x82, B: 0xf6}.Sequence()

	if want := "\x1b[38;2;59;130;246m"; got != want {
		t.Errorf("Sequence wrote %q, want %q", got, want)
	}
	if strings.Contains(got, "38;5;") {
		t.Errorf("Sequence wrote %q, want the direct-RGB form", got)
	}
}

// TestBackgroundSequenceIsABackground covers the one difference between the two forms,
// since writing a background as a foreground paints text rather than the ground behind
// it.
func TestBackgroundSequenceIsABackground(t *testing.T) {
	got := RGB{R: 0x10, G: 0x10, B: 0x10}.BackgroundSequence()

	if want := "\x1b[48;2;16;16;16m"; got != want {
		t.Errorf("BackgroundSequence wrote %q, want %q", got, want)
	}
}

func TestTCellStyleCarriesThemeAndRoleColors(t *testing.T) {
	theme := themeWith(t, "#3b82f6", "#101010")
	p := NewPalette(true, GroundDark, &theme)

	fg, bg, _ := p.BaseStyle().Decompose()
	if r, g, b := fg.RGB(); r != 59 || g != 130 || b != 246 {
		t.Errorf("base foreground = (%d, %d, %d), want (59, 130, 246)", r, g, b)
	}
	if r, g, b := bg.RGB(); r != 16 || g != 16 || b != 16 {
		t.Errorf("base background = (%d, %d, %d), want (16, 16, 16)", r, g, b)
	}

	styleFG, _, _ := p.Style(RoleFailure).Decompose()
	want := RoleTableFor(GroundDark)[RoleFailure].TCellColor()
	if styleFG != want {
		t.Errorf("failure foreground = %v, want %v", styleFG, want)
	}
	if got := NewPalette(false, GroundDark, nil).BaseStyle(); got != tcell.StyleDefault {
		t.Errorf("palette-off base style = %v, want default", got)
	}
}

// TestThemeNamesSaysWhatWasAskedFor covers the diagnostic, since a theme whose values
// are empty needs a sentence rather than nothing.
func TestThemeNamesSaysWhatWasAskedFor(t *testing.T) {
	none := themeWith(t, "", "")
	if got := ThemeNames(none); !strings.Contains(got, "terminal theme") {
		t.Errorf("a theme naming nothing reads as %q", got)
	}

	both := themeWith(t, "#000000", "#ffffff")
	got := ThemeNames(both)
	for _, want := range []string{"#000000", "#ffffff"} {
		if !strings.Contains(got, want) {
			t.Errorf("the sentence %q does not carry %q", got, want)
		}
	}
}

// TestPaneStyleFallsBackWithNoColoursConfigured covers the default a session built
// with neither PaneActiveColor nor PaneDoneColor gets: the pane bar colours exactly
// as it did before this existed, which is not at all.
func TestPaneStyleFallsBackWithNoColoursConfigured(t *testing.T) {
	p := NewPalette(true, GroundDark, nil)

	for _, state := range []string{"running", "done", "", "something else"} {
		if _, ok := p.PaneStyle(state); ok {
			t.Errorf("PaneStyle(%q) with no pane colours configured reports ok, want false", state)
		}
	}
}

// TestPaneStyleUsesTheConfiguredColours covers the two states a reader can configure,
// and that they are not the same colour as each other or as no colour at all.
func TestPaneStyleUsesTheConfiguredColours(t *testing.T) {
	active := RGB{R: 0x11, G: 0x22, B: 0x33}
	done := RGB{R: 0x44, G: 0x55, B: 0x66}
	p := NewPalette(true, GroundDark, nil).WithPaneColors(&active, &done)

	runningStyle, ok := p.PaneStyle("running")
	if !ok {
		t.Fatal(`PaneStyle("running") reports ok = false, want true`)
	}
	if fg, _, _ := runningStyle.Decompose(); fg != active.TCellColor() {
		t.Errorf("running foreground = %v, want %v", fg, active.TCellColor())
	}

	doneStyle, ok := p.PaneStyle("done")
	if !ok {
		t.Fatal(`PaneStyle("done") reports ok = false, want true`)
	}
	if fg, _, _ := doneStyle.Decompose(); fg != done.TCellColor() {
		t.Errorf("done foreground = %v, want %v", fg, done.TCellColor())
	}

	if _, ok := p.PaneStyle(""); ok {
		t.Error(`PaneStyle("") reports ok = true, want false: neither state applies`)
	}
}

// TestPaneStyleIsOffWithColourOff covers the rule every other role already follows:
// a palette with colour off writes no colour, and the pane bar is not an exception
// carved out of it.
func TestPaneStyleIsOffWithColourOff(t *testing.T) {
	active := RGB{R: 0x11, G: 0x22, B: 0x33}
	p := NewPalette(false, GroundDark, nil).WithPaneColors(&active, &active)

	if _, ok := p.PaneStyle("running"); ok {
		t.Error("PaneStyle reports ok = true with colour off, want false")
	}
}
